apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-web
  namespace: platform-demo
  labels:
    app.kubernetes.io/part-of: k8s-observability-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-web
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s