apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-web
  labels:
    app.kubernetes.io/name: demo-web
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-web
